### ISSUE TITLE
socket.error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by 1043423268** [geek-ai/MAgent#11]
zx@zx-MS-7A38:~/project/zx/MAgent$ python examples/train_pursuit.py
Traceback (most recent call last):
  File "examples/train_pursuit.py", line 133, in <module>
    target_update=1000, train_freq=4
  File "/home/zx/project/zx/MAgent/python/magent/model.py", line 153, in __init__
    listener = multiprocessing.connection.Listener(addr)
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/connection.py", line 132, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/connection.py", line 256, in __init__
    self._socket.bind(address)
  File "/home/zx/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
2017-12-12 21:01:39.301346: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Process Process-1:
Traceback (most recent call last):
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zx/project/zx/MAgent/python/magent/model.py", line 297, in model_client
    conn = multiprocessing.connection.Client(addr)
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/connection.py", line 169, in Client
    c = SocketClient(address)
  File "/home/zx/anaconda2/lib/python2.7/multiprocessing/connection.py", line 308, in SocketClient
    s.connect(address)
  File "/home/zx/anaconda2/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

**Comment by ewanlee** [comment]
I also encountered this problem. Could you tell me how to solve it? Thx~

**Comment by Kipsora** [comment]
@ewanlee You could reboot your computer or simply find whether any program has occupied the port that the render uses (by default it is 9030). This issue is basically caused by a specific port being occupied by the render.

**Comment by ewanlee** [comment]
Thank you very much, the problem was indeed solved after I restarted the computer.
