### ISSUE TITLE
Can't run it in Linux

### ISSUE THREAD

**Issue by axi345** [geek-ai/MAgent#47]
I used Ubuntu 14.02 and Anaconda with Python 3.5.2 to run this project. I downloaded this repository and run these commands:

cd MAgent
sudo apt-get install cmake libboost-system-dev libjsoncpp-dev libwebsocketpp-dev
bash build.sh
export PYTHONPATH=$(pwd)/python:$PYTHONPATH

But there raised some errors and I couldn't install the python package successfully. So I copied the file "Magent" to my python project and used pycharm to mark the "Python" file in it as the Sources Root. When I run the file "api_demo.py", it showed some error massages:

/home/sean/anaconda3/bin/python3.6 /home/sean/DRL/MAgent/examples/train_pursuit.py
Traceback (most recent call last):
  File "/home/sean/DRL/MAgent/examples/train_pursuit.py", line 11, in <module>
    import magent
  File "/home/sean/DRL/MAgent/python/magent/__init__.py", line 2, in <module>
    from . import utility
  File "/home/sean/DRL/MAgent/python/magent/utility.py", line 12, in <module>
    from magent.builtin.rule_model import RandomActor
  File "/home/sean/DRL/MAgent/python/magent/builtin/rule_model/__init__.py", line 2, in <module>
    from .rush import RushPredator
  File "/home/sean/DRL/MAgent/python/magent/builtin/rule_model/rush.py", line 7, in <module>
    from magent.c_lib import _LIB, as_int32_c_array, as_float_c_array
  File "/home/sean/DRL/MAgent/python/magent/c_lib.py", line 42, in <module>
    _LIB = _load_lib()
  File "/home/sean/DRL/MAgent/python/magent/c_lib.py", line 21, in _load_lib
    lib = ctypes.CDLL(path_to_so_file, ctypes.RTLD_GLOBAL)
  File "/home/sean/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sean/DRL/MAgent/python/magent/../../build/libmagent.so: cannot open shared object file: No such file or directory

Process finished with exit code 1

It seems that my file miss some resources. But I use files completely copied from git. Maybe I missed some steps. I need some help to use the repository. o_o

**Comment by Kipsora** [comment]
It seems that the build process was failed and thus libmagent.so did not exist. Can you provide the build messages as well?

**Comment by Kipsora** [comment]
The build log shows that your C++ compiler does not support LLVM and hence the compilation cannot be completed. You may manually upgrade your C++ compiler and rebuild the project.

You may also refer my environment:
```bash
$ uname -a
Linux Kipsora-All-Series 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4
15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

$ cmake --version
cmake version 3.5.1
```
