### ISSUE TITLE
when I run "python examples/train_pursuit.py --train", there are the errors

### ISSUE THREAD

**Issue by Gezx** [geek-ai/MAgent#64]
Traceback (most recent call last):
  File "examples/train_pursuit.py", line 11, in <module>
    import magent
ModuleNotFoundError: No module named 'magent'
(base) gezhixin@gezhixin-virtual-machine:~/MAgent-master$ export PYTHONPATH=$PYTHONPATH:/home/gezhixin/MAgent-master/python
(base) gezhixin@gezhixin-virtual-machine:~/MAgent-master$ python examples/train_pursuit.py --train
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:521: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:522: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/gezhixin/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "examples/train_pursuit.py", line 133, in <module>
    target_update=1000, train_freq=4
  File "/home/gezhixin/MAgent-master/python/magent/model.py", line 154, in __init__
    listener = multiprocessing.connection.Listener(addr)
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/connection.py", line 438, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/connection.py", line 576, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
WARNING:tensorflow:From /home/gezhixin/MAgent-master/python/magent/builtin/tf_model/dqn.py:185: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
From /home/gezhixin/MAgent-master/python/magent/builtin/tf_model/dqn.py:185: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-02 10:47:48.774911: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Process Process-1:
Traceback (most recent call last):
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/gezhixin/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gezhixin/MAgent-master/python/magent/model.py", line 303, in model_client
    model = RLModel(**model_args)
  File "/home/gezhixin/MAgent-master/python/magent/builtin/tf_model/dqn.py", line 143, in __init__
    self.replay_buf_view     = ReplayBuffer(shape=(memory_size,) + self.view_space)
  File "/home/gezhixin/MAgent-master/python/magent/builtin/common.py", line 9, in __init__
    self.buffer = np.empty(shape=shape, dtype=dtype)
MemoryError: Unable to allocate array with shape (4194304, 10, 10, 5) and data type float32
Exception ignored in: <bound method ProcessingModel.__del__ of <magent.model.ProcessingModel object at 0x7fdc5e27dd68>>
Traceback (most recent call last):
  File "/home/gezhixin/MAgent-master/python/magent/model.py", line 285, in __del__
    quit()
  File "/home/gezhixin/anaconda3/lib/python3.6/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: None

**Comment by Kipsora** [comment]
The issue is caused by MemoryError, which means that your memory may be too small to run the example.

**Comment by Gezx** [comment]
thank you,I will try it.
