### ISSUE TITLE
Compatibility problem with Python3

### ISSUE THREAD

**Issue by leonfg** [geek-ai/MAgent#9]
examples/show_arrange.py can not run in Python3.5 and Python3.6 on Ubuntu 16.04:
Traceback (most recent call last):
  File "examples/show_arrange.py", line 22, in <module>
    PyGameRenderer().start(Server(messages=args.mess, mode=args.mode), grid_size=3.5)
  File "/data/Work/MAgent/python/magent/renderer/server/arrange_server.py", line 345, in __init__
    generate_map(mode, env, map_size, food_handle, handles, messages, font)
  File "/data/Work/MAgent/python/magent/renderer/server/arrange_server.py", line 282, in generate_map
    draw(base_x, base_y, scale, data)
  File "/data/Work/MAgent/python/magent/renderer/server/arrange_server.py", line 270, in draw
    for x in range(start_x, start_x + scale):
TypeError: 'float' object cannot be interpreted as an integer.

Python2.7 is OK.

**Comment by KornbergFresnel** [comment]
Thanks for submitting issues. We have fixed this bug (for python3).
